### ISSUE TITLE
Internal error show me Ticket issued on First instalation

### ISSUE THREAD

**Issue by mortzaCFT** [ITSec-Chile/Waf2Py#20]
Hello its my first time using this tool and i having a error.:
![Screenshot 2024-12-30 222245](https://github.com/user-attachments/assets/c384768e-de44-4715-b853-0a70861e667e)

the error message:
```
Internal error
Ticket issued: [Waf2Py/192.168.70.175.2024-12-30.13-50-13.475031bb-d1cb-4eea-9fa8-f8ec364190be](https://192.168.70.157:62443/admin/default/ticket/Waf2Py/192.168.70.175.2024-12-30.13-50-13.475031bb-d1cb-4eea-9fa8-f8ec364190be)
```
and when i go to the ticket i see such things:
![Screenshot 2024-12-30 222343](https://github.com/user-attachments/assets/fc205c2f-703c-446d-9da7-7d22631e243f)

the full log:
```
<html>
<body>
<!--StartFragment--><h2 style="margin: 10px 0px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 40px; color: rgb(51, 51, 51); text-rendering: optimizelegibility; font-size: 31.5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Error ticket for "Waf2Py"</h2><h3 style="margin: 10px 0px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 40px; color: rgb(51, 51, 51); text-rendering: optimizelegibility; font-size: 24.5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Ticket ID</h3><p style="margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">192.168.70.175.2024-12-30.13-50-13.475031bb-d1cb-4eea-9fa8-f8ec364190be</p><h4 style="margin: 10px 0px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 20px; color: rgb(51, 51, 51); text-rendering: optimizelegibility; font-size: 17.5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&lt;class 'ImportError'&gt; No module named applications.Waf2Py.modules.psutil</h4><h3 style="margin: 10px 0px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 40px; color: rgb(51, 51, 51); text-rendering: optimizelegibility; font-size: 24.5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Version</h3>
web2py™ | Version 2.20.4-stable+timestamp.2020.05.03.05.18.50
-- | --
Python 3.11.2: /usr/bin/python3 (prefix: /usr)

</div><!--EndFragment-->
</body>
</html>Error ticket for "Waf2Py"
Ticket ID
192.168.70.175.2024-12-30.13-50-13.475031bb-d1cb-4eea-9fa8-f8ec364190be

<class 'ImportError'> No module named applications.Waf2Py.modules.psutil
Version
web2py™	Version 2.20.4-stable+timestamp.2020.05.03.05.18.50
Python	Python 3.11.2: /usr/bin/python3 (prefix: /usr)
Traceback
1.
2.
3.
4.
5.
6.
7.
8.
9.
10.
11.
12.
13.
14.
15.
16.
17.
18.
19.
20.
21.
22.
Traceback (most recent call last):
  File "/home/www-data/waf2py_community/gluon/custom_import.py", line 78, in custom_importer
    result = sys.modules[modules_prefix]
             ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'applications.Waf2Py.modules.psutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www-data/waf2py_community/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File ["/home/www-data/waf2py_community/applications/Waf2Py/controllers/default.py"](https://192.168.70.157:62443/admin/edit/Waf2Py/controllers/default.py), line 4, in <module>
    import stuffs
  File "/home/www-data/waf2py_community/gluon/custom_import.py", line 73, in custom_importer
    new_mod = base_importer(
              ^^^^^^^^^^^^^^
  File "/home/www-data/waf2py_community/applications/Waf2Py/modules/stuffs.py", line 10, in <module>
    import psutil
  File "/home/www-data/waf2py_community/gluon/custom_import.py", line 80, in custom_importer
    raise ImportError("No module named %s" % modules_prefix)
ImportError: No module named applications.Waf2Py.modules.psutil
Error snapshot help
ImportError(No module named applications.Waf2Py.modules.psutil)

inspect attributes

Frames
File /home/www-data/waf2py_community/gluon/restricted.py in restricted at line 219 code arguments variables

File /home/www-data/waf2py_community/applications/Waf2Py/controllers/default.py in <module> at line 4 code arguments variables

File /home/www-data/waf2py_community/gluon/custom_import.py in custom_importer at line 73 code arguments variables

File /home/www-data/waf2py_community/applications/Waf2Py/modules/stuffs.py in <module> at line 10 code arguments variables

File /home/www-data/waf2py_community/gluon/custom_import.py in custom_importer at line 80 code arguments variables

Function argument list
(name='psutil', globals={'__builtins__': {'ArithmeticError': <class 'ArithmeticError'>, 'AssertionError': <class 'AssertionError'>, 'AttributeError': <class 'AttributeError'>, 'BaseException': <class 'BaseException'>, 'BaseExceptionGroup': <class 'BaseExceptionGroup'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'BufferError': <class 'BufferError'>, 'BytesWarning': <class 'BytesWarning'>, 'ChildProcessError': <class 'ChildProcessError'>, ...}, '__cached__': '/home/www-data/waf2py_community/applications/Waf2Py/modules/__pycache__/stuffs.cpython-311.pyc', '__doc__': None, '__file__': '/home/www-data/waf2py_community/applications/Waf2Py/modules/stuffs.py', '__loader__': <_frozen_importlib_external.SourceFileLoader object>, '__name__': 'applications.Waf2Py.modules.stuffs', '__package__': 'applications.Waf2Py.modules', '__spec__': ModuleSpec(name='applications.Waf2Py.modules.stu...community/applications/Waf2Py/modules/stuffs.py'), 'os': <module 'os' (frozen)>, 'random': <module 'random' from '/usr/lib/python3.11/random.py'>, ...}, locals={'__builtins__': {'ArithmeticError': <class 'ArithmeticError'>, 'AssertionError': <class 'AssertionError'>, 'AttributeError': <class 'AttributeError'>, 'BaseException': <class 'BaseException'>, 'BaseExceptionGroup': <class 'BaseExceptionGroup'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'BufferError': <class 'BufferError'>, 'BytesWarning': <class 'BytesWarning'>, 'ChildProcessError': <class 'ChildProcessError'>, ...}, '__cached__': '/home/www-data/waf2py_community/applications/Waf2Py/modules/__pycache__/stuffs.cpython-311.pyc', '__doc__': None, '__file__': '/home/www-data/waf2py_community/applications/Waf2Py/modules/stuffs.py', '__loader__': <_frozen_importlib_external.SourceFileLoader object>, '__name__': 'applications.Waf2Py.modules.stuffs', '__package__': 'applications.Waf2Py.modules', '__spec__': ModuleSpec(name='applications.Waf2Py.modules.stu...community/applications/Waf2Py/modules/stuffs.py'), 'os': <module 'os' (frozen)>, 'random': <module 'random' from '/usr/lib/python3.11/random.py'>, ...}, fromlist=None, level=0)

Code listing
75.
76.
77.
78.
79.
80.
81.
82.
83.
84.
                modules_prefix += "." + itemname
                if result is None:
                    try:
                        result = sys.modules[modules_prefix]
                    except KeyError:
                        raise ImportError("No module named %s" % modules_prefix)
            return result
        else:
            # "from x import a, b, ..."
            pname = "%s.%s" % (modules_prefix, name)
Variables
builtinImportError	<class 'ImportError'>
modules_prefix	'applications.Waf2Py.modules.psutil'
Context
locals request session response

In file: /home/www-data/waf2py_community/applications/Waf2Py/controllers/default.py
1.
<code object <module> at 0x7f68a098be80, file "/home/www-data/waf2py_community/applications/Waf2Py/controllers/default.py", line 1>
```

As i said its my first time using this tool , i haivng error from web2py.
Please help me i need your help!

**Comment by mortzaCFT** [comment]
For who didnt succeed:
The modules that i didn't installed i installed the psutil and its fixed.
Thanks the creator i using this good thing!
with regards
mortza.
